### ISSUE TITLE
"transverse" in the docs and comments

### ISSUE THREAD

**Issue by jeffreykegler** [jddurand/c-marpaESLIF#11]
Sometimes the worst person to ask about a language is a native speaker, since they judge things by the speech of whatever bog they grew up in. :-)  So when I saw you use the word "transverse" in a sense I did not recognize, I did my homework, looking in dictionaries, etc.  You use it (I think) in the sense of "applying across [some domain]", and that sense isn't in any dictionary I consulted.

So I was just about to file an issue saying that "transverse" does not occur in English in this sense, when by pure change I listened to a commentary on "Whiter Shade of Pale", where an LA musicologist used "transverse" as follows: "the past became a fungible toolbox [...] which transversed the classical and popular music worlds".  So, [here](https://youtu.be/iIV1uSevHSE?t=1056), caught in the wild, was a use of "transverse" by (apparently) a native speaker in the same sense you use it.

The musicologist is a PhD and apparently a postmodernist or influenced by them.  So I suspect this sense of "transverse" is from the postmodern lexicon.

All of which is a long preamble to this:  I stumbled over the work "transverse" in your docs and it took me a while to puzzle out what you meant by it.  I've actually read in philosophy, including a fair amount of Deleuze, so I think if the word was strange to me, it's likely to puzzle a lot of other readers even among those otherwise fluent in English.  I'd like to revise the docs to eliminate the use of "transverse" in favor of locutions more like to be familiar to those who read tech docs.

**Comment by jddurand** [comment]
Indeed, it is easy to spot I am not a native speaker ;)
Your understanding of "transverse" was right, and I see two mentions of "transverse" in the doc.. Please feel free to remove them, I should not have used that term...
(Thanks to have mention Deleuze! I am not competent enough in philosophy though ;))

**Comment by jeffreykegler** [comment]
Thanks.  I will wait for your response to #10 before doing the "transverse" rewrites.  Otherwise the two sets of changes may overlap, so that a 1-click merge isn't possible, and a complicated merge becomes necessary.

**Comment by jeffreykegler** [comment]
I am going to file a separate pull request for the rewrites, and therefore am closing this issue.
