### ISSUE TITLE
Blog / document ESLIF timings

### ISSUE THREAD

**Issue by jeffreykegler** [jddurand/c-marpaESLIF#13]
I am opening this issue to ask questions for my blog post on issue #9.

**Comment by jeffreykegler** [comment]
@jddurand Thanks for the code and the final timings in https://github.com/jddurand/c-marpaESLIF/issues/9#issuecomment-1206665905.  Could you give me a link for the minimal ESLIF grammar and actions in the source?

**Comment by jeffreykegler** [comment]
Also, please blog it yourself, if you are so inclined.

**Comment by jddurand** [comment]
Will try to find the time (I will be off for three weeks starting august 14th).

**Comment by jeffreykegler** [comment]
I've decided to prioritize work on the Libmarpa API doc -- making it self-contained, instead on dependent on the Marpa::R2 docs as a prerequisite.  This means I won't get to blogging the ESLIF in the near future.  Therefore I am closing this issue.
